version: '3.9'

services:
  node:
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
