version: '3.9'

services:
  node:
    container_name: node
    build: .
    read_only: true
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8000:3001
    env_file:
      - ./.env
    # depends_on:
    #   - mongod_db
    # environment:
    #   DB_URI: mongodb://node_demo_app:27017
    #   JWT_SECRET_KEY: JWT_SECRET_KEY_HERE
    #   REFRESH_TOKEN_SECRET_KEY: REFRESH_TOKEN_SECRET_KEY_HERE

    #   EMAIL_HOST: smtp.ethereal.email
    #   EMAIL_PORT: 587
    #   EMAIL_USER: qgiutwyya4hdvwms@ethereal.email
    #   EMAIL_PASS: 37UNpnjWdzTNBUdsmc
    #   EMAIL_FROM: info@nodejs.com

    #   AWS_REGION: AWS_REGION_HERE
    #   AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID_HERE
    #   AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY_HERE

    # mongod_db:
    #   container_name: node_demo_app
    #   image: mongo:6.0.2-focal
    #   restart: always
    #   volumes:
    #     - mongo_db:/data/db

    # volumes:
    #   mongo_db: {}

