version: '3.9'

services:
  node:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      # - MONGO_IP=
      # - MONGO_PORT=
      - MONGO_USER=prod_user
      - MONGO_PASSWORD=prod_password
    command: node src/app.js
    volumes:
      - ./:/app
      - /app/node_modules
    # env_file:
    #   - ./.env.production

  mongo_db:
    volumes:
      - mongo_prod_vol:/data/db

volumes:
  mongo_prod_vol: {}
